/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.13
 * Generated at: 2018-01-10 14:50:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class account_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1515343008188L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1515500264084L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n");
      out.write("   <!DOCTYPE HTML>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>TGN - The Game Nation</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"css/loginForm.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel='stylesheet' id='prettyphoto-css'  href=\"css/prettyPhoto.css\" type='text/css' media='all'>\r\n");
      out.write("    <link href=\"css/fontello.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Quattrocento:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <style>\r\n");
      out.write("    body {\r\n");
      out.write("        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    <link href=\"css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/favicon.ico\">\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/validator.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.scrollTo-1.4.2-min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.localscroll-1.2.7-min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("          $(document).ready(function(){\r\n");
      out.write("            $(\"a[rel^='prettyPhoto']\").prettyPhoto();\r\n");
      out.write("          });\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <body>\r\n");
      out.write("\t    <div class=\"navbar-wrapper\">\r\n");
      out.write("      <div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("        <div class=\"navbar-inner\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->\r\n");
      out.write("            <a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\"> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </a>\r\n");
      out.write("            <h1 class=\"brand\"><a href=\"index.jsp\">TGN - The Game Nation</a></h1>\r\n");
      out.write("            <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->\r\n");
      out.write("            <nav class=\"pull-right nav-collapse collapse\">\r\n");
      out.write("              <ul id=\"menu-main\" class=\"nav\">\r\n");
      out.write("                \r\n");
      out.write("                <li><a title=\"portfolio\" href=\"index.jsp\">Home</a></li> <!-- this will be 3 most recent or something... -->\r\n");
      out.write("                \r\n");
      out.write("                <li><a title=\"services\" href=\"topics.jsp\">All topics</a></li>\r\n");
      out.write("                \r\n");
      out.write("     \t\t\t");
 if ((session.getAttribute("email") != null) && (((String) session.getAttribute("email")).compareTo("")!=0)) { 
      out.write("           \r\n");
      out.write("\t                <li><a title=\"news\" href=\"liveChat.jsp\">Live chat</a></li> <!-- if we can't make it work site-wide -->\r\n");
      out.write("               \t\t<li><a title=\"team\" href=\"account.jsp\">Account</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                ");
 if ((session.getAttribute("email") == null) || (((String) session.getAttribute("email")).compareTo("")==0)) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a title=\"login\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a title=\"logout\" href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t              \r\n");
      out.write("              </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write(" \t");
 if((session.getAttribute("email") == null)||(session.getAttribute("email").equals(""))) { 
 	    out.println("<script type=\"text/javascript\">");
 	    out.println("alert('To access this page, you must be logged in!');");
 	    out.println("location='login.jsp';");
 	   	out.println("</script>");
 	} else { 
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \t<br>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<form method=\"post\" onsubmit=\"return validateRegistration()\" action=\"/TGN/Registration\" style=\" text-align:center\">\r\n");
      out.write("\t\t\t<h3>Account</h3><br>\r\n");
      out.write("\t\t\t\t<input style=\"width: 200px;\" type=\"text\" id=\"first_name\" name=\"first_name\" value=\"\" placeholder=\"Name\" required><br>\r\n");
      out.write("\t\t\t\t<input style=\"width: 200px;\" type=\"text\" id=\"last_name\" name=\"last_name\" value=\"\" placeholder=\"Last name\" required><br>\r\n");
      out.write("\t\t\t\t<input style=\"width: 200px;\" type=\"text\" id=\"email\" name=\"email\" value=\"\" placeholder=\"Email\" required><br>\r\n");
      out.write("\t\t\t\t<input style=\"width: 200px;\" type=\"password\" id=\"pass\" name=\"pass\"  value=\"\" placeholder=\"Password\" required><br>\r\n");
      out.write("\t\t\t\t<input style=\"width: 200px;\" type=\"password\" id=\"pass1\" name=\"pass1\"  value=\"\" placeholder=\"Repeat password\" required><br>\r\n");
      out.write("\t\t\t\t<input style=\"height: 50px; width: 100px;\" type=\"submit\" class=\"btn btn-1\" value=\"Register\" />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<center><p id=\"feedback_reg\"></p></center>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t        ");
String exists = "";
						if(request.getAttribute("exists")!= null) {
							exists = (String) request.getAttribute("exists");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br /><center>");
      out.print(exists );
      out.write("</center>\r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
String noMatch = "";
						if(request.getAttribute("noMatch")!= null) {
							noMatch = (String) request.getAttribute("noMatch");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br /><center>");
      out.print(noMatch );
      out.write("</center>\r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h3>Already have an account? Login <a href=\"login.jsp\">here</a>.</h3>\r\n");
      out.write("\t\t\t\r\n");
      out.write("        </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
 } 
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div class=\"footer-wrapper\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <footer>\r\n");
      out.write("          <small>&copy; 2018 The Game Nation. All rights reserved.</small>\r\n");
      out.write("        </footer>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/bootstrap.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/site.js\"></script>\r\n");
      out.write("    \t\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
      out.write('\r');
      out.write('\n');
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
